### ISSUE TITLE
Backtrace in Ember client

### ISSUE THREAD

**Issue by cfcohen** [worldforge/ember#31]
Hopefully the following backtrace will be useful to you:

```
(gdb) 
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff6152859 in __GI_abort () at abort.c:79
#2  0x00007ffff6152729 in __assert_fail_base (fmt=0x7ffff62e8588 <error: Cannot access memory at address 0x7ffff62e8588>, 
    assertion=0x555556978490 <error: Cannot access memory at address 0x555556978490>, file=0x555556978368 <error: Cannot access memory at address 0x555556978368>, line=232, 
    function=<optimized out>) at assert.c:92
#3  0x00007ffff6163f36 in __GI___assert_fail (assertion=0x555556978490 <error: Cannot access memory at address 0x555556978490>, 
    file=0x555556978368 <error: Cannot access memory at address 0x555556978368>, line=232, function=0x555556978420 <error: Cannot access memory at address 0x555556978420>)
    at assert.c:101
#4  0x000055555638210c in Ogre::AxisAlignedBox::setExtents(float, float, float, float, float, float) ()
#5  0x0000555556381dc1 in Ogre::AxisAlignedBox::AxisAlignedBox(float, float, float, float, float, float) ()
#6  0x00005555563dc688 in Ember::OgreView::Convert::toOgre(WFMath::AxisBox<3> const&) ()
#7  0x00005555564c5aa9 in Ember::OgreView::Model::ModelMount::scaleNode(WFMath::AxisBox<3> const*) ()
#8  0x00005555564c569f in Ember::OgreView::Model::ModelMount::rescale(WFMath::AxisBox<3> const*) ()
#9  0x00005555564c7a33 in Ember::OgreView::Model::ModelAttachment::updateScale() ()
#10 0x00005555564c82e1 in Ember::OgreView::Model::ModelAttachment::model_Reloaded() ()
#11 0x00005555564d1435 in sigc::bound_mem_functor0<void, Ember::OgreView::Model::ModelAttachment>::operator()() const ()
#12 0x00005555564cf912 in sigc::adaptor_functor<sigc::bound_mem_functor0<void, Ember::OgreView::Model::ModelAttachment> >::operator()() const ()
#13 0x00005555564cdbc0 in sigc::internal::slot_call<sigc::bound_mem_functor0<void, Ember::OgreView::Model::ModelAttachment>, void>::call_it(sigc::internal::slot_rep*) ()
#14 0x00005555561fb14d in sigc::internal::signal_emit0<void, sigc::nil>::emit(sigc::internal::signal_impl*) ()
#15 0x000055555620aa36 in sigc::signal0<void, sigc::nil>::emit() const ()
#16 0x0000555556463e9b in Ember::OgreView::Model::Model::loadAssets() ()
#17 0x0000555556485d84 in Ember::OgreView::Model::ModelDefinition::reloadModels() ()
#18 0x0000555556485d0f in Ember::OgreView::Model::ModelDefinition::reloadModels()::{lambda()#1}::operator()() const ()
#19 0x0000555556486fda in std::_Function_handler<void (), Ember::OgreView::Model::ModelDefinition::reloadModels()::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
#20 0x00005555563f3b76 in std::function<void ()>::operator()() const ()
#21 0x00007ffff7c4c6fc in Eris::EventService::runOnMainThread(std::function<void ()> const&, std::shared_ptr<bool>)::{lambda()#1}::operator()() const ()
   from /usr/local/lib/liberis-1.4.so.0
#22 0x00007ffff7c4cf1e in std::_Function_handler<void (), Eris::EventService::runOnMainThread(std::function<void ()> const&, std::shared_ptr<bool>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /usr/local/lib/liberis-1.4.so.0
#23 0x00005555563f3b76 in std::function<void ()>::operator()() const ()
#24 0x00007ffff7c4ccc3 in Eris::EventService::processOneHandler() () from /usr/local/lib/liberis-1.4.so.0
#25 0x00005555561f6a05 in Ember::Application::mainLoop() ()
#26 0x00005555561f8e62 in Ember::Application::start() ()
#27 0x0000555556222d07 in main ()
```

Entire stack built from source using checkouts from Github.  All checkouts on master except CEGUI, which didn't build, so I reverted to orgin/v0-8.  Ubuntu 20.04, gcc 9.3.0.

Not sure if the problem was my build, but I couldn't get the binary distributions to work either.   The apt-repository packages claimed that they weren't properly signed, and the dpkg distribution lacked the dependencies.  Not really seeking support, just trying to be helpful.

**Comment by erikogenvik** [comment]
Thanks, do you know which Git SHA-1 of Ember this was with?

Also, if you could post the content of ~/.local/share/ember/ember.log it would be helpful?
